In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1= np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [12]:
dframe1

X         Y         Z
0 -1.810211  0.210775 -0.795315
1 -2.233620 -0.001454  0.028456
2 -1.247460 -0.455268  0.431716
3 -1.778988  0.397271 -0.007587

In [13]:
dframe2

Y         Q         X
0  0.455728  2.086450 -0.735358
1  0.383191  0.368084  1.424513
2  1.343524 -0.023183  0.811770

In [14]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -1.810211  0.210775 -0.795315
1       NaN -2.233620 -0.001454  0.028456
2       NaN -1.247460 -0.455268  0.431716
3       NaN -1.778988  0.397271 -0.007587
0  2.086450 -0.735358  0.455728       NaN
1  0.368084  1.424513  0.383191       NaN
2 -0.023183  0.811770  1.343524       NaN

In [15]:
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -1.810211  0.210775 -0.795315
1       NaN -2.233620 -0.001454  0.028456
2       NaN -1.247460 -0.455268  0.431716
3       NaN -1.778988  0.397271 -0.007587
4  2.086450 -0.735358  0.455728       NaN
5  0.368084  1.424513  0.383191       NaN
6 -0.023183  0.811770  1.343524       NaN